baseURL = "http://localhost:1414/"
languageCode = "en-us"
theme = "diary"
title = "s. s. crawford"
copyright = "2025 s. s. crawford"

[outputs]
  home = ["HTML", "RSS"]

[params]
  subtitle = "A writer."
  author = "s. s. crawford"
  enableAutoDarkMode=true

[menu]
  [[menu.main]]
    name = "Stories"
    url = "/stories/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
