baseURL = "https://sscrawford.net"
description = "S. S. Crawford is an author of short horror stories."
enableRobotsTXT = true
languageCode = "en-us"
theme = "diary"
title = "s. s. crawford"
copyright = "2025 s. s. crawford"

[outputs]
  home = ["HTML", "RSS"]

[params]
  author = "s. s. crawford"
  enableAutoDarkMode=true
  favicon = "favicon.png"

[menu]
  [[menu.main]]
    name = "Stories"
    url = "/stories/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "Acknowledgments"
    url = "/acknowledgments/"
    weight = 3

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark.renderer]
    unsafe = true